### ISSUE TITLE
Game gets stuck on limbo between landing and taking off

### ISSUE THREAD

**Issue by AshtonSparx** [bizzlemip/BiggerLobby#1]
When taking off from a planet, we can't land or take off and get stuck in limbo.

**Comment by foxfoxfoxgay** [comment]
Please attach the BepInEx/LogOutput.log file

**Comment by foxfoxfoxgay** [comment]
Issue is caused by an incorrect installation
please ensure that all players have lc api in **BepInEx**/plugins,
and all players have audio in BepInEx/Bundles
